### ISSUE TITLE
What else displayed in new relic other than the transaction name?

### ISSUE THREAD

**Issue by bionimic** [digiaonline/lumen-newrelic#19]
Hi, 

I want to ask about this package, Is it only to display transaction name in new relic like the image below? "PROD - /App\Http\Controllers\Record\HistoryController@index (https://localhost/barracuda/record/history/80bc6643-3305-11)"

![Screen Shot 2020-05-21 at 1 54 23 PM](https://user-images.githubusercontent.com/9911699/82528240-e6d85f80-9b6a-11ea-896f-6f707ea19194.png)

Can we trace transaction stack trace for the "PROD - /App\Http\Controllers\Record\HistoryController@index (https://localhost/barracuda/record/history/80bc6643-3305-11)" transaction?

The only I can see when I click the magnifying icon is the image below:

![Screen Shot 2020-05-21 at 1 57 59 PM](https://user-images.githubusercontent.com/9911699/82528354-230bc000-9b6b-11ea-8db0-d895bea00fcc.png)

Thanks

**Comment by Jalle19** [comment]
I'm not really sure what you're asking here. This library is just a thin wrapper on top of the New Relic PHP plugin, so if you wanna know what exactly is being sent to New Relic you need to check their documentation. This library allows you to set the transaction name (since it's not usually auto-detected correctly for Lumen apps) and report exceptions correctly, not much else.
